"""
Explizite Maßnahmen pro Fehlermodus – Agent-Output.

Der Agent analysiert Fehlermodi mit RPZ >= 100 und ergänzt diese Datei
oder ruft insert_measures_for_fehlermodus direkt auf.
generate_measures.py lädt dieses Modul – liefert [] wenn keine Maßnahmen definiert.
"""

# Maßnahmen pro Fehlermodus (KOMP-001 bis KOMP-007, Ethylacetat-Anlage).
# generate_measures.py ruft get_measures_for_fehlermodus auf und spielt über insert_measures ein.
_MEASURES = {
    # KOMP-001: Synthesereaktor R-101
    "KOMP-001-F2-FM1": [  # Runaway, S=9,O=3,D=3, RPZ=81
        {"name": "FI am Kühlwasser", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Durchflussmessung am Kühlwassereinlauf mit Alarm bei Unterschreitung",
         "ziel": "D", "S_neu": 9, "O_neu": 3, "D_neu": 2,
         "begruendung": "D sinkt: Direkte Durchflussüberwachung erkennt Ausfall vor Temperaturanstieg",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Stellungsüberwachung Dampfventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Endlagenschalter oder Stellungsrückmeldung am Dampfventil Heizmantel",
         "ziel": "D", "S_neu": 9, "O_neu": 3, "D_neu": 2,
         "begruendung": "Erkennt klemmendes Ventil",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "PSV/BSV Prüfintervall", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Jährliche Prüfung PSV-410 und BSV-411 gemäß BetrSichV",
         "ziel": "O", "S_neu": 9, "O_neu": 2, "D_neu": 3,
         "begruendung": "O sinkt durch funktionsfähige Sicherheitseinrichtungen",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-001-F2-FM2": [  # Unterdruck, S=6,O=2,D=4, RPZ=48
        {"name": "VSV-412 Prüfintervall", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Prüfung Vakuumbrecher VSV-412",
         "ziel": "O", "S_neu": 6, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt durch funktionsfähigen Vakuumbrecher",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Abkühl-SOP", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Verfahrensanweisung für kontrolliertes Abkühlen, max. Gradient",
         "ziel": "O", "S_neu": 6, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt durch definierte Abkühlvorgabe",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-001-F1-FM3": [  # Überfüllung, S=8,O=3,D=4, RPZ=96
        {"name": "Redundante Füllstandsmessung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Zweiter unabhängiger Füllstandstransmitter oder LSHH 1oo2",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Unabhängige Überfüllsicherung",
         "hinweis": "⚡ höherer Aufwand, 💰 moderat"},
        {"name": "Dosier-Freigabeprotokoll", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Checkliste vor Dosierung, Vier-Augen-Prinzip bei kritischen Chargen",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch kontrollierte Dosierung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-001-F1-FM4": [  # Falsche Zusammensetzung, S=7,O=4,D=5, RPZ=140
        {"name": "Chargenfreigabe-Prozess", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Dokumentierte Chargenfreigabe vor Reaktionsstart, Prüfung Vorcharge",
         "ziel": "O", "S_neu": 7, "O_neu": 3, "D_neu": 5,
         "begruendung": "O sinkt durch Freigabeprotokoll",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Inline-Qualitätsprüfung Edukte", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Schnellprüfung Edukte vor Dosierung (pH, Dichte, etc.)",
         "ziel": "D", "S_neu": 7, "O_neu": 4, "D_neu": 3,
         "begruendung": "D sinkt: Verunreinigungen vor Reaktion erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 moderat"},
    ],
    "KOMP-001-F2-FM5": [  # Thermische Fehlfunktion, S=6,O=3,D=5, RPZ=90
        {"name": "TI am Kühlwasser-Rücklauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Temperaturanzeige am Kühlwasser-Rücklauf, Alarm bei < 10 °C",
         "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Erkennt zu kaltes Kühlwasser vor Vereisung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Sole-Freigabeprotokoll", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Checkliste vor Aktivierung Sole-Notkühlung",
         "ziel": "O", "S_neu": 6, "O_neu": 2, "D_neu": 5,
         "begruendung": "O sinkt: Versehentliche Sole-Aktivierung vermeiden",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-001-F3-FM6": [  # Undichtheit, S=8,O=2,D=4, RPZ=64
        {"name": "Regelmäßige Inspektion", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Wanddickenmessung, Sichtprüfung Flansche bei Revision",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Degradation vor Leckage erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Leckage-Detektor am Mannloch", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Tropfwanne oder Leitfähigkeitsmessung unter kritischen Stutzen",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    # KOMP-002: Heizmantel HM-101
    "KOMP-002-F1-FM1": [
        {"name": "Stellungsüberwachung Dampfventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Endlagenschalter oder Stellungsrückmeldung am Dampfventil",
         "ziel": "D", "S_neu": 9, "O_neu": 2, "D_neu": 2,
         "begruendung": "D sinkt: Klemmendes Ventil erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Regelmäßige Stellungsprüfung", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Jährliche Funktionsprüfung Dampfventil inkl. Stellungsprüfung",
         "ziel": "O", "S_neu": 9, "O_neu": 1, "D_neu": 3,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-002-F1-FM2": [
        {"name": "Trap-Inspektion bei Revision", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Inspektion Kondensatablauf (Trap) bei Revisionsöffnung",
         "ziel": "O", "S_neu": 5, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-002-F1-FM3": [
        {"name": "PI am Dampfmantel", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Druckanzeige am Dampfmantel, Alarm bei Unterschreitung",
         "ziel": "D", "S_neu": 5, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Drucküberwachung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-002-F1-FM4": [
        {"name": "Stellungsüberwachung Dampfventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Erkennt geschlossenes Ventil bei Heizbedarf",
         "ziel": "D", "S_neu": 6, "O_neu": 2, "D_neu": 2,
         "begruendung": "D sinkt: Fehlende Dampfzufuhr erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-002-F1-FM5": [
        {"name": "PI am Dampfmantel", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Druckanzeige am Mantel, Alarm bei > 6.5 bar",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Manteldruck-Überwachung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "PSH am Mantel", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Druckschalter hoch, schaltet Dampfzufuhr bei Überschreitung ab",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Automatische Abschaltung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Prüfintervall Dampfdruckregler", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Jährliche Kalibrierung Druckregler am Dampfmantel",
         "ziel": "O", "S_neu": 8, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Kennzeichnung Dampfleitung", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Klare Kennzeichnung Niederdruck 6 bar, Freigabeprotokoll vor Inbetriebnahme",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt: Verwechslung vermeiden",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-002-F2-FM6": [
        {"name": "Leckageüberwachung am Mantel", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Leitfähigkeitsmessung oder Kondensatüberwachung zur Erkennung Prozesseintritt",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ höherer Aufwand, 💰 moderat"},
        {"name": "Regelmäßige Inspektion", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Wanddickenmessung, Sichtprüfung bei Revision",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Degradation vor Leckage erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Betriebsanweisung Leckagezeichen", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Hinweis auf Leckagezeichen (Geruch, Tropfen), Meldeweg",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Personal sensibilisiert",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    # KOMP-003: Kühlmantel KM-101
    "KOMP-003-F1-FM1": [
        {"name": "FI am Kühlwassereinlauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Durchflussmessung (Flow Indicator) am Kühlwassereinlauf mit Alarm bei Unterschreitung",
         "ziel": "D", "S_neu": 9, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Durchflussüberwachung erkennt Ausfall vor Temperaturanstieg",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Stellungsüberwachung Kühlwasserventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Endlagenschalter oder Stellungsrückmeldung am Kühlwassereinlaufventil",
         "ziel": "D", "S_neu": 9, "O_neu": 2, "D_neu": 3,
         "begruendung": "Erkennt geschlossenes Ventil",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Wartungsplan Kühlwasserpumpe", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Inspektion und Wartung der Kühlwasserpumpe",
         "ziel": "O", "S_neu": 9, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-003-F1-FM2": [
        {"name": "TI am Kühlwasser-Rücklauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Temperaturanzeige am Kühlwasser-Rücklauf mit Alarm bei < 10 °C",
         "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Erkennt zu kaltes Kühlwasser vor Vereisung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Sole-Freigabeprotokoll", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Checkliste vor Aktivierung der Sole-Notkühlung, Vier-Augen-Prinzip",
         "ziel": "O", "S_neu": 6, "O_neu": 2, "D_neu": 5,
         "begruendung": "O sinkt: Versehentliche Sole-Aktivierung vermeiden",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-003-F1-FM3": [
        {"name": "Δp-Monitoring über Packung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Differenzdruck-Messung über Kühlmantel, Alarm bei Anstieg",
         "ziel": "D", "S_neu": 5, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Fouling erhöht Δp",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Reinigungsintervall dokumentieren", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Feste Revisionsintervalle für Kühlmantel-Reinigung",
         "ziel": "O", "S_neu": 5, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Reinigung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-003-F2-FM4": [
        {"name": "Leitfähigkeitsmessung Kondensat", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Leitfähigkeitsüberwachung im Kühlwasserkreislauf erkennt Prozesseintritt",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ höherer Aufwand, 💰 moderat"},
        {"name": "Wanddickenmessung bei Revision", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Regelmäßige Wanddickenmessung am Mantel bei Revisionsöffnung",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Erkennt Degradation vor Leckage",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    # KOMP-004: Rührwerk RW-101
    "KOMP-004-F1-FM1": [
        {"name": "Redundante Drehzahlüberwachung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Zweiter Drehzahlsensor oder Frequenzumrichter-Rückmeldung",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 2,
         "begruendung": "D sinkt: Zuverlässigere Stillstandserkennung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Wartungsplan Lager/Rührer", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Inspektion Lager und Rührerblatt",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-004-F1-FM2": [
        {"name": "LSLL Trockenlaufschutz", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "LSLL (Level Switch Low Low) – Rührwerk abschalten bei Mindestfüllstand",
         "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Verhindert Trockenlauf",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Drehzahlbegrenzung bei niedrigem Füllstand", "stop_kategorie": "T", "abe_kategorie": "A",
         "beschreibung": "SIC-404 begrenzt Drehzahl automatisch bei LIC < Schwellwert",
         "ziel": "O", "S_neu": 6, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt: Kavitation wird vermieden",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-004-F2-FM3": [
        {"name": "Leckage-Detektor an Wellenabdichtung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Tropfwanne mit Leitfähigkeits- oder Niveauüberwachung unter der Welle",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Gleitringdichtung mit Sperrmedium-Überwachung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Doppelgleitringdichtung mit Drucküberwachung Sperrmedium",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 4,
         "begruendung": "D sinkt: Leckage an innerem Ring erkennbar",
         "hinweis": "⚡ höherer Aufwand, 💰 höher"},
        {"name": "Monatliche Sichtprüfung Welle", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Dokumentierte Sichtprüfung auf Tropfen an der Welle",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 4,
         "begruendung": "D sinkt: Regelmäßige Prüfung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    # KOMP-005: Destillationskolonne K-101
    "KOMP-005-F1-FM1": [
        {"name": "Δp-Monitoring über Packung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Differenzdruck-Messung über Kolonne, Alarm bei Anstieg",
         "ziel": "D", "S_neu": 5, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Fouling erhöht Δp",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Reinigungsintervall Packung", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Feste Revisionsintervalle für Packungsreinigung",
         "ziel": "O", "S_neu": 5, "O_neu": 2, "D_neu": 5,
         "begruendung": "O sinkt durch präventive Reinigung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-005-F1-FM2": [
        {"name": "PIC an Kolonnenkopf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Druckanzeige und -regler direkt am Kolonnenkopf",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Kolonnenüberwachung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Kühlwasserüberwachung Kondensatoren", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "FI am Kühlwasser KD-101/102, Alarm bei Ausfall",
         "ziel": "O", "S_neu": 8, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt: Kondensatorausfall wird vermieden",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-005-F2-FM3": [
        {"name": "Dichtheitsprüfung bei Revision", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Druckprüfung oder Helium-Leckprüfung bei Revisionsöffnung",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Leckagen vor Inbetriebnahme erkannt",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Flansch-Montageanweisung", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "SOP für Flanschmontage mit Anzugsmomenten und Dichtungsprüfung",
         "ziel": "O", "S_neu": 8, "O_neu": 1, "D_neu": 5,
         "begruendung": "O sinkt: Falsche Montage vermieden",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    # KOMP-006: Kondensator KD-101
    "KOMP-006-F1-FM1": [
        {"name": "FI am Kühlwassereinlauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Durchflussmessung am Kühlwassereinlauf mit Alarm bei Unterschreitung",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Durchflussüberwachung erkennt Ausfall vor Druckanstieg",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Stellungsüberwachung Kühlwasserventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Endlagenschalter oder Stellungsrückmeldung am Kühlwasserventil",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "Erkennt geschlossenes Ventil",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Wartungsplan Kühlwasserpumpe", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Inspektion und Wartung der Kühlwasserpumpe",
         "ziel": "O", "S_neu": 8, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-006-F1-FM2": [
        {"name": "Δp-Monitoring über Kondensator", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Differenzdruck-Messung über Kondensator, Alarm bei Anstieg",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Fouling erhöht Δp"},
        {"name": "Reinigungsintervall", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Feste Revisionsintervalle für Kondensator-Reinigung",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Reinigung"},
    ],
    "KOMP-006-F1-FM3": [
        {"name": "TI am Kühlwasser-Rücklauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Temperaturanzeige am Kühlwasser-Rücklauf, Alarm bei < 10 °C",
         "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Erkennt zu kaltes Kühlwasser vor Vereisung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-006-F1-FM4": [
        {"name": "Leitfähigkeitsmessung Kühlwasser", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Leitfähigkeitsüberwachung im Kühlwasserkreislauf erkennt Produkteintritt",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ höherer Aufwand, 💰 moderat"},
        {"name": "Regelmäßige Inspektion", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Rohrprüfung bei Revisionsöffnung",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Degradation vor Leckage erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    # KOMP-007: Kondensator KD-102
    "KOMP-007-F1-FM1": [
        {"name": "FI am Kühlwassereinlauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Durchflussmessung am Kühlwassereinlauf mit Alarm bei Unterschreitung",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3, "begruendung": "D sinkt: Direkte Durchflussüberwachung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Stellungsüberwachung Kühlwasserventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Endlagenschalter oder Stellungsrückmeldung", "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3, "begruendung": "Erkennt geschlossenes Ventil",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Wartungsplan Kühlwasserpumpe", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Inspektion und Wartung", "ziel": "O", "S_neu": 8, "O_neu": 1, "D_neu": 4, "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-007-F1-FM2": [
        {"name": "Δp-Monitoring über Kondensator", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Differenzdruck-Messung, Alarm bei Anstieg", "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3, "begruendung": "D sinkt: Fouling erhöht Δp",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Reinigungsintervall", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Feste Revisionsintervalle für Kondensator-Reinigung", "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4, "begruendung": "O sinkt durch präventive Reinigung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-007-F1-FM3": [
        {"name": "TI am Kühlwasser-Rücklauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Temperaturanzeige am Rücklauf, Alarm bei < 10 °C", "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 3, "begruendung": "D sinkt: Erkennt zu kaltes Kühlwasser",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-007-F1-FM4": [
        {"name": "Leitfähigkeitsmessung Kühlwasser", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Leitfähigkeitsüberwachung erkennt Produkteintritt", "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3, "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ höherer Aufwand, 💰 moderat"},
        {"name": "Regelmäßige Inspektion", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Rohrprüfung bei Revisionsöffnung", "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4, "begruendung": "D sinkt: Degradation vor Leckage erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    # ─── KOMP-008 bis KOMP-047: explizite Maßnahmen für alle hoch bewerteten Fehlermodi ───
    "KOMP-008-F2-FM3": [
        {"name": "Leckagesensor / Tropfwanne unter DV-101", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Leitfähigkeitsmessung oder Tropfwanne unter Destillatvorlage DV-101, Alarm bei Medienaustritt",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Leckage in Ex-Zone früh erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Regelmäßige Inspektion Flansche/Stutzen DV-101", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Sichtprüfung und Dichtheitsprüfung bei Revision",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-009-F2-FM3": [
        {"name": "Leckagesensor / Tropfwanne unter DV-102", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Leitfähigkeitsmessung oder Tropfwanne unter Destillatvorlage DV-102 (Wasser), Alarm bei Austritt",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Leckage in Ex-Zone früh erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Regelmäßige Inspektion DV-102", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Sichtprüfung und Dichtheitsprüfung bei Revision",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-010-F1-FM1": [
        {"name": "Plausibilitätsprüfung TIC-401 mit TI-401a/401b", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Abweichungsalarm wenn TIC-401 von TI-401a oder TI-401b um Schwellwert abweicht",
         "ziel": "D", "S_neu": 9, "O_neu": 3, "D_neu": 2,
         "begruendung": "D sinkt: Frozen Value erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Jährliche Kalibrierung TIC-401", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Kalibrierung und Funktionsprüfung Temperaturregelkreis Reaktor",
         "ziel": "O", "S_neu": 9, "O_neu": 2, "D_neu": 3,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-010-F1-FM2": [
        {"name": "Plausibilitätsprüfung TIC mit Redundanz-TI", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Abweichungsalarm bei Drift zwischen TIC-401 und TI-401a/401b",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Drift erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Kalibrierintervall TIC-401 dokumentieren", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Feste Kalibrierintervalle gemäß Hersteller/BetrSichV",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-010-F1-FM3": [
        {"name": "Stellungsüberwachung Heiz-/Kühlventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Endlagenschalter oder Stellungsrückmeldung am Stellglied des TIC-401",
         "ziel": "D", "S_neu": 9, "O_neu": 3, "D_neu": 2,
         "begruendung": "D sinkt: Stuck-at erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Regelmäßige Stellungsprüfung", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Funktionsprüfung Stellventil inkl. Stellungsprüfung bei Revision",
         "ziel": "O", "S_neu": 9, "O_neu": 2, "D_neu": 3,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-011-F1-FM1": [
        {"name": "Plausibilitätsprüfung TI-401a mit TIC-401 / TI-401b", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Abweichungsalarm wenn TI-401a von TIC-401 oder TI-401b abweicht",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Frozen Value erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Kalibrierintervall TI-401a", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Kalibrierung Mantel-Eingangstemperatur",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-011-F1-FM2": [
        {"name": "Abweichungsalarm TI-401a vs. TIC-401", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Alarm bei Abweichung zwischen Redundanz-TI und TIC über Schwellwert",
         "ziel": "D", "S_neu": 7, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Drift erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-012-F1-FM1": [
        {"name": "Plausibilitätsprüfung 2-of-3 Temperatur", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Abweichungsalarm wenn eine der drei Messstellen (TIC-401, TI-401a, TI-401b) abweicht",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Ausfall einer Redundanzstelle erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Kalibrierintervall TI-401b", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Kalibrierung Mantel-Ausgangstemperatur",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-013-F1-FM1": [
        {"name": "Plausibilitätsprüfung PIC-402 mit TIC-401", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Alarm bei Druckanstieg ohne Temperaturanstieg (Runaway-Plausibilität)",
         "ziel": "D", "S_neu": 9, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Frozen Value bei Druck erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Jährliche Kalibrierung PIC-402", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Kalibrierung und Funktionsprüfung Druckmessung Reaktor",
         "ziel": "O", "S_neu": 9, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "PSV/BSV Prüfintervall einhalten", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Jährliche Prüfung PSV-410 und BSV-411 gemäß BetrSichV",
         "ziel": "O", "S_neu": 9, "O_neu": 2, "D_neu": 3,
         "begruendung": "O sinkt: Letzte Barriere funktionsfähig",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-015-F1-FM1": [
        {"name": "Periodische Funktionsprüfung LSHH-403", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Prüfung Schaltpunkt 480 L und Ansprechverhalten (z. B. jährlich)",
         "ziel": "O", "S_neu": 9, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt: Überfüllsicherung zuverlässig",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Reinigung/Kalibrierung Vibrationsschalter", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Verschmutzung entfernen, Schaltpunkt prüfen",
         "ziel": "O", "S_neu": 9, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt: Verklebung vermieden",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-015-F1-FM3": [
        {"name": "Fail-safe Anordnung LSHH-403", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Verkabelung so, dass Leitungsbruch/Signalausfall zu Abschaltung führt (Überfüllsicherung aktiv)",
         "ziel": "O", "S_neu": 9, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt: Ausfall führt zu sicherem Zustand",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Periodische Prüfung Signalweg LSHH", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Funktionsprüfung inkl. Verkabelung und Relais",
         "ziel": "D", "S_neu": 9, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Ausfall erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-016-F1-FM1": [
        {"name": "Plausibilitätsprüfung SIC-404 mit TIC-401", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Alarm bei Drehzahl Null/Abweichung bei gleichzeitigem Temperaturanstieg (Stillstand)",
         "ziel": "D", "S_neu": 7, "O_neu": 4, "D_neu": 3,
         "begruendung": "D sinkt: Frozen Value / Stillstand erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Wartungsplan VFD und Drehzahlsensor", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Inspektion Frequenzumrichter und Rückmeldung",
         "ziel": "O", "S_neu": 7, "O_neu": 3, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-017-F1-FM1": [
        {"name": "Jährliche Prüfung PSV-410 gemäß BetrSichV", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Funktionsprüfung, Ansprechdruck, Dichtheit – dokumentiert",
         "ziel": "O", "S_neu": 10, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt: Ventil funktionsfähig",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Inspektion Sitz und Dichtflächen bei Abnahme", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Sichtprüfung auf Verklebung, Korrosion, Fremdkörper bei jeder Öffnung",
         "ziel": "O", "S_neu": 10, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt: Fail-to-open-Risiko reduziert",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-017-F1-FM2": [
        {"name": "Sichtprüfung PSV-Sitz bei Revision/Abnahme", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Erosion/Kavitation am Sitz prüfen, bei Verschleiß Ventil tauschen",
         "ziel": "D", "S_neu": 10, "O_neu": 4, "D_neu": 3,
         "begruendung": "D sinkt: Verschleiß vor nächstem Abblasen erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Tauschintervall bei häufigem Ansprechen", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Bei bekanntem Verschleiß (z. B. Medien) kürzeres Prüf-/Tauschintervall festlegen",
         "ziel": "O", "S_neu": 10, "O_neu": 3, "D_neu": 4,
         "begruendung": "O sinkt durch präventiven Tausch",
         "hinweis": "⚡ schnell umsetzbar, 💰 moderat"},
    ],
    "KOMP-018-F1-FM1": [
        {"name": "PSV-410 Prüfintervall einhalten", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Primäre Druckentlastung PSV-410 zuverlässig halten, damit BSV selten beansprucht wird",
         "ziel": "O", "S_neu": 10, "O_neu": 1, "D_neu": 5,
         "begruendung": "O sinkt: BSV nur Backup",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "BSV-Inspektion bei Revisionsöffnung", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Berstscheibe auf Alterung/Korrosion prüfen, Dimensionierung dokumentieren",
         "ziel": "D", "S_neu": 10, "O_neu": 2, "D_neu": 5,
         "begruendung": "D sinkt: Degradation erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-019-F1-FM1": [
        {"name": "Jährliche Prüfung VSV-412", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Funktionsprüfung Vakuumbrecher -0.8 bar, Verklebung/Korrosion prüfen",
         "ziel": "O", "S_neu": 9, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt: VSV funktionsfähig",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Dokumentation Prüfergebnis VSV-412", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Prüfprotokoll in Instandhaltung führen",
         "ziel": "D", "S_neu": 9, "O_neu": 3, "D_neu": 4,
         "begruendung": "D sinkt: Nachvollziehbarkeit",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-020-F1-FM1": [
        {"name": "Periodische Funktionsprüfung NOT-AUS-R101", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Prüfung: Betätigung führt zu Abschaltung aller Antriebe und Schließen der Ventile",
         "ziel": "O", "S_neu": 10, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt: NOT-AUS zuverlässig",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Verkabelung und Relais prüfen", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Bei Revision Verkabelung und Schaltkreise NOT-AUS prüfen",
         "ziel": "D", "S_neu": 10, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Defekte erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-025-F1-FM2": [
        {"name": "Leckagesensor Auffangwanne AW-200 prüfen", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Sicherstellen, dass Leckage an P-202 von AW-200 erfasst wird",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Leckage erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Regelmäßige Dichtungsprüfung P-202", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Membran und Flansche bei Wartung prüfen",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-026-F1-FM1": [
        {"name": "Durchflussüberwachung Katalysatordosierung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Durchflussmessung oder Mengenüberwachung KD-203 mit Alarm bei Überschreitung",
         "ziel": "D", "S_neu": 7, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Überdosierung erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "TIC-401/PIC-402 als Rückfallebene", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Temperatur-/Druckalarm bei Runaway durch Überdosierung",
         "ziel": "D", "S_neu": 7, "O_neu": 3, "D_neu": 4,
         "begruendung": "D sinkt: Indirekte Erkennung",
         "hinweis": "⚡ bereits vorhanden, 💰 gering"},
    ],
    "KOMP-026-F1-FM2": [
        {"name": "Leckagesensor AW-200 und Meldeweg", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Leckagesensor in Auffangwanne muss Schwefelsäure erfassen, Alarm an Leitstand",
         "ziel": "D", "S_neu": 9, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Leckage sofort erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Regelmäßige Inspektion KD-203 Schläuche/Dichtungen", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Sichtprüfung auf Risse, Tropfen – dokumentiert",
         "ziel": "O", "S_neu": 9, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-033-F1-FM1": [
        {"name": "Periodische Funktionsprüfung Leckagesensor AW-200", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Prüfung: Sensor spricht an bei Test (z. B. Wasser)",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 4,
         "begruendung": "D sinkt: Sensorausfall erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Redundanz oder Ersatzstrategie dokumentieren", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Bei Sensorausfall: Runde/Inspektion bis Reparatur",
         "ziel": "O", "S_neu": 8, "O_neu": 3, "D_neu": 4,
         "begruendung": "O sinkt: Lücke abgedeckt",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-034-F1-FM1": [
        {"name": "NK-301 Notkühlung periodisch prüfen", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Funktionsprüfung Notkühlsystem (Fail-to-start vermeiden)",
         "ziel": "O", "S_neu": 10, "O_neu": 1, "D_neu": 3,
         "begruendung": "O sinkt: Backup einsatzbereit",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "FI/TI Kühlwasser KW-301 überwachen", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Durchfluss und Temperatur Kühlwasser mit Alarm bei Ausfall",
         "ziel": "D", "S_neu": 10, "O_neu": 2, "D_neu": 2,
         "begruendung": "D sinkt: Kühlausfall sofort erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-037-F1-FM1": [
        {"name": "FI am Kühlwassereinlauf KW-301", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Durchflussmessung mit Alarm bei Unterschreitung – erkennt No Flow",
         "ziel": "D", "S_neu": 10, "O_neu": 2, "D_neu": 2,
         "begruendung": "D sinkt: Kühlausfall sofort erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "NK-301 Notkühlung Funktionsprüfung", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Prüfung: Notkühlung startet bei Simulation KW-Ausfall",
         "ziel": "O", "S_neu": 10, "O_neu": 1, "D_neu": 3,
         "begruendung": "O sinkt: Backup zuverlässig",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-038-F1-FM1": [
        {"name": "Periodische Funktionsprüfung NK-301", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßig: Pumpe starten, Solefluss prüfen, Ventilstellung prüfen",
         "ziel": "O", "S_neu": 10, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt: Fail-to-start vermieden",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Alarmierung bei NK-Start (KW-Ausfall)", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Meldung an Leitstand wenn Notkühlung zugeschaltet wird",
         "ziel": "D", "S_neu": 10, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Ereignis erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-047-F1-FM1": [
        {"name": "Jährliche Prüfung PSV-310 Dampfverteiler", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Funktionsprüfung Sicherheitsventil 7 bar, Ansprechdruck, Dichtheit",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt: Ventil funktionsfähig",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "PI-301 Drucküberwachung Dampf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Druckanzeige Dampfeingang – Alarm bei Annäherung an 7 bar",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Überdruck erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-047-F1-FM2": [
        {"name": "Sichtprüfung PSV-310 bei Revision", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Sitz und Dichtflächen prüfen, bei Leckage Ventil wechseln",
         "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Leckage bei Abnahme erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Druckverlust/Verbrauch überwachen", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Anomalie im Dampfverbrauch kann auf Leckage hindeuten",
         "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 4,
         "begruendung": "D sinkt: Indirekte Erkennung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
}


def get_measures_for_fehlermodus(fehler_id: str, fehlermodus: str, komponente: str) -> list:
    """
    Liefert explizite Maßnahmen für den Fehlermodus.
    Rückgabe: Liste von Maßnahme-Dicts oder [] wenn keine definiert.
    """
    return _MEASURES.get(fehler_id, [])
