"""
Explizite Maßnahmen pro Fehlermodus – Agent-Output.

Der Agent analysiert Fehlermodi mit RPZ >= 100 und ergänzt diese Datei
oder ruft insert_measures_for_fehlermodus direkt auf.
generate_measures.py lädt dieses Modul – liefert [] wenn keine Maßnahmen definiert.
"""

# Maßnahmen pro Fehlermodus (KOMP-001 bis KOMP-007, Ethylacetat-Anlage).
# generate_measures.py ruft get_measures_for_fehlermodus auf und spielt über insert_measures ein.
_MEASURES = {
    # KOMP-001: Synthesereaktor R-101
    "KOMP-001-F2-FM1": [  # Runaway, S=9,O=3,D=3, RPZ=81
        {"name": "FI am Kühlwasser", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Durchflussmessung am Kühlwassereinlauf mit Alarm bei Unterschreitung",
         "ziel": "D", "S_neu": 9, "O_neu": 3, "D_neu": 2,
         "begruendung": "D sinkt: Direkte Durchflussüberwachung erkennt Ausfall vor Temperaturanstieg",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Stellungsüberwachung Dampfventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Endlagenschalter oder Stellungsrückmeldung am Dampfventil Heizmantel",
         "ziel": "D", "S_neu": 9, "O_neu": 3, "D_neu": 2,
         "begruendung": "Erkennt klemmendes Ventil",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "PSV/BSV Prüfintervall", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Jährliche Prüfung PSV-410 und BSV-411 gemäß BetrSichV",
         "ziel": "O", "S_neu": 9, "O_neu": 2, "D_neu": 3,
         "begruendung": "O sinkt durch funktionsfähige Sicherheitseinrichtungen",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-001-F2-FM2": [  # Unterdruck, S=6,O=2,D=4, RPZ=48
        {"name": "VSV-412 Prüfintervall", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Prüfung Vakuumbrecher VSV-412",
         "ziel": "O", "S_neu": 6, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt durch funktionsfähigen Vakuumbrecher",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Abkühl-SOP", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Verfahrensanweisung für kontrolliertes Abkühlen, max. Gradient",
         "ziel": "O", "S_neu": 6, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt durch definierte Abkühlvorgabe",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-001-F1-FM3": [  # Überfüllung, S=8,O=3,D=4, RPZ=96
        {"name": "Redundante Füllstandsmessung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Zweiter unabhängiger Füllstandstransmitter oder LSHH 1oo2",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Unabhängige Überfüllsicherung",
         "hinweis": "⚡ höherer Aufwand, 💰 moderat"},
        {"name": "Dosier-Freigabeprotokoll", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Checkliste vor Dosierung, Vier-Augen-Prinzip bei kritischen Chargen",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch kontrollierte Dosierung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-001-F1-FM4": [  # Falsche Zusammensetzung, S=7,O=4,D=5, RPZ=140
        {"name": "Chargenfreigabe-Prozess", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Dokumentierte Chargenfreigabe vor Reaktionsstart, Prüfung Vorcharge",
         "ziel": "O", "S_neu": 7, "O_neu": 3, "D_neu": 5,
         "begruendung": "O sinkt durch Freigabeprotokoll",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Inline-Qualitätsprüfung Edukte", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Schnellprüfung Edukte vor Dosierung (pH, Dichte, etc.)",
         "ziel": "D", "S_neu": 7, "O_neu": 4, "D_neu": 3,
         "begruendung": "D sinkt: Verunreinigungen vor Reaktion erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 moderat"},
    ],
    "KOMP-001-F2-FM5": [  # Thermische Fehlfunktion, S=6,O=3,D=5, RPZ=90
        {"name": "TI am Kühlwasser-Rücklauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Temperaturanzeige am Kühlwasser-Rücklauf, Alarm bei < 10 °C",
         "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Erkennt zu kaltes Kühlwasser vor Vereisung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Sole-Freigabeprotokoll", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Checkliste vor Aktivierung Sole-Notkühlung",
         "ziel": "O", "S_neu": 6, "O_neu": 2, "D_neu": 5,
         "begruendung": "O sinkt: Versehentliche Sole-Aktivierung vermeiden",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-001-F3-FM6": [  # Undichtheit, S=8,O=2,D=4, RPZ=64
        {"name": "Regelmäßige Inspektion", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Wanddickenmessung, Sichtprüfung Flansche bei Revision",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Degradation vor Leckage erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Leckage-Detektor am Mannloch", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Tropfwanne oder Leitfähigkeitsmessung unter kritischen Stutzen",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    # KOMP-002: Heizmantel HM-101
    "KOMP-002-F1-FM1": [
        {"name": "Stellungsüberwachung Dampfventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Endlagenschalter oder Stellungsrückmeldung am Dampfventil",
         "ziel": "D", "S_neu": 9, "O_neu": 2, "D_neu": 2,
         "begruendung": "D sinkt: Klemmendes Ventil erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Regelmäßige Stellungsprüfung", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Jährliche Funktionsprüfung Dampfventil inkl. Stellungsprüfung",
         "ziel": "O", "S_neu": 9, "O_neu": 1, "D_neu": 3,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-002-F1-FM2": [
        {"name": "Trap-Inspektion bei Revision", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Inspektion Kondensatablauf (Trap) bei Revisionsöffnung",
         "ziel": "O", "S_neu": 5, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-002-F1-FM3": [
        {"name": "PI am Dampfmantel", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Druckanzeige am Dampfmantel, Alarm bei Unterschreitung",
         "ziel": "D", "S_neu": 5, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Drucküberwachung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-002-F1-FM4": [
        {"name": "Stellungsüberwachung Dampfventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Erkennt geschlossenes Ventil bei Heizbedarf",
         "ziel": "D", "S_neu": 6, "O_neu": 2, "D_neu": 2,
         "begruendung": "D sinkt: Fehlende Dampfzufuhr erkennbar",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-002-F1-FM5": [
        {"name": "PI am Dampfmantel", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Druckanzeige am Mantel, Alarm bei > 6.5 bar",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Manteldruck-Überwachung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "PSH am Mantel", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Druckschalter hoch, schaltet Dampfzufuhr bei Überschreitung ab",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Automatische Abschaltung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Prüfintervall Dampfdruckregler", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Jährliche Kalibrierung Druckregler am Dampfmantel",
         "ziel": "O", "S_neu": 8, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Kennzeichnung Dampfleitung", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Klare Kennzeichnung Niederdruck 6 bar, Freigabeprotokoll vor Inbetriebnahme",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt: Verwechslung vermeiden",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-002-F2-FM6": [
        {"name": "Leckageüberwachung am Mantel", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Leitfähigkeitsmessung oder Kondensatüberwachung zur Erkennung Prozesseintritt",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ höherer Aufwand, 💰 moderat"},
        {"name": "Regelmäßige Inspektion", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Wanddickenmessung, Sichtprüfung bei Revision",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Degradation vor Leckage erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Betriebsanweisung Leckagezeichen", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Hinweis auf Leckagezeichen (Geruch, Tropfen), Meldeweg",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Personal sensibilisiert",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    # KOMP-003: Kühlmantel KM-101
    "KOMP-003-F1-FM1": [
        {"name": "FI am Kühlwassereinlauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Durchflussmessung (Flow Indicator) am Kühlwassereinlauf mit Alarm bei Unterschreitung",
         "ziel": "D", "S_neu": 9, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Durchflussüberwachung erkennt Ausfall vor Temperaturanstieg",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Stellungsüberwachung Kühlwasserventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Endlagenschalter oder Stellungsrückmeldung am Kühlwassereinlaufventil",
         "ziel": "D", "S_neu": 9, "O_neu": 2, "D_neu": 3,
         "begruendung": "Erkennt geschlossenes Ventil",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Wartungsplan Kühlwasserpumpe", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Inspektion und Wartung der Kühlwasserpumpe",
         "ziel": "O", "S_neu": 9, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-003-F1-FM2": [
        {"name": "TI am Kühlwasser-Rücklauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Temperaturanzeige am Kühlwasser-Rücklauf mit Alarm bei < 10 °C",
         "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Erkennt zu kaltes Kühlwasser vor Vereisung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Sole-Freigabeprotokoll", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Checkliste vor Aktivierung der Sole-Notkühlung, Vier-Augen-Prinzip",
         "ziel": "O", "S_neu": 6, "O_neu": 2, "D_neu": 5,
         "begruendung": "O sinkt: Versehentliche Sole-Aktivierung vermeiden",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-003-F1-FM3": [
        {"name": "Δp-Monitoring über Packung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Differenzdruck-Messung über Kühlmantel, Alarm bei Anstieg",
         "ziel": "D", "S_neu": 5, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Fouling erhöht Δp",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Reinigungsintervall dokumentieren", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Feste Revisionsintervalle für Kühlmantel-Reinigung",
         "ziel": "O", "S_neu": 5, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Reinigung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-003-F2-FM4": [
        {"name": "Leitfähigkeitsmessung Kondensat", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Leitfähigkeitsüberwachung im Kühlwasserkreislauf erkennt Prozesseintritt",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ höherer Aufwand, 💰 moderat"},
        {"name": "Wanddickenmessung bei Revision", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Regelmäßige Wanddickenmessung am Mantel bei Revisionsöffnung",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Erkennt Degradation vor Leckage",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    # KOMP-004: Rührwerk RW-101
    "KOMP-004-F1-FM1": [
        {"name": "Redundante Drehzahlüberwachung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Zweiter Drehzahlsensor oder Frequenzumrichter-Rückmeldung",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 2,
         "begruendung": "D sinkt: Zuverlässigere Stillstandserkennung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Wartungsplan Lager/Rührer", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Inspektion Lager und Rührerblatt",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-004-F1-FM2": [
        {"name": "LSLL Trockenlaufschutz", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "LSLL (Level Switch Low Low) – Rührwerk abschalten bei Mindestfüllstand",
         "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Verhindert Trockenlauf",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Drehzahlbegrenzung bei niedrigem Füllstand", "stop_kategorie": "T", "abe_kategorie": "A",
         "beschreibung": "SIC-404 begrenzt Drehzahl automatisch bei LIC < Schwellwert",
         "ziel": "O", "S_neu": 6, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt: Kavitation wird vermieden",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-004-F2-FM3": [
        {"name": "Leckage-Detektor an Wellenabdichtung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Tropfwanne mit Leitfähigkeits- oder Niveauüberwachung unter der Welle",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Gleitringdichtung mit Sperrmedium-Überwachung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Doppelgleitringdichtung mit Drucküberwachung Sperrmedium",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 4,
         "begruendung": "D sinkt: Leckage an innerem Ring erkennbar",
         "hinweis": "⚡ höherer Aufwand, 💰 höher"},
        {"name": "Monatliche Sichtprüfung Welle", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Dokumentierte Sichtprüfung auf Tropfen an der Welle",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 4,
         "begruendung": "D sinkt: Regelmäßige Prüfung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    # KOMP-005: Destillationskolonne K-101
    "KOMP-005-F1-FM1": [
        {"name": "Δp-Monitoring über Packung", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Differenzdruck-Messung über Kolonne, Alarm bei Anstieg",
         "ziel": "D", "S_neu": 5, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Fouling erhöht Δp",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Reinigungsintervall Packung", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Feste Revisionsintervalle für Packungsreinigung",
         "ziel": "O", "S_neu": 5, "O_neu": 2, "D_neu": 5,
         "begruendung": "O sinkt durch präventive Reinigung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-005-F1-FM2": [
        {"name": "PIC an Kolonnenkopf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Druckanzeige und -regler direkt am Kolonnenkopf",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Kolonnenüberwachung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Kühlwasserüberwachung Kondensatoren", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "FI am Kühlwasser KD-101/102, Alarm bei Ausfall",
         "ziel": "O", "S_neu": 8, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt: Kondensatorausfall wird vermieden",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-005-F2-FM3": [
        {"name": "Dichtheitsprüfung bei Revision", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Druckprüfung oder Helium-Leckprüfung bei Revisionsöffnung",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Leckagen vor Inbetriebnahme erkannt",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
        {"name": "Flansch-Montageanweisung", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "SOP für Flanschmontage mit Anzugsmomenten und Dichtungsprüfung",
         "ziel": "O", "S_neu": 8, "O_neu": 1, "D_neu": 5,
         "begruendung": "O sinkt: Falsche Montage vermieden",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    # KOMP-006: Kondensator KD-101
    "KOMP-006-F1-FM1": [
        {"name": "FI am Kühlwassereinlauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Durchflussmessung am Kühlwassereinlauf mit Alarm bei Unterschreitung",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Durchflussüberwachung erkennt Ausfall vor Druckanstieg",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Stellungsüberwachung Kühlwasserventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Endlagenschalter oder Stellungsrückmeldung am Kühlwasserventil",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "Erkennt geschlossenes Ventil",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Wartungsplan Kühlwasserpumpe", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Inspektion und Wartung der Kühlwasserpumpe",
         "ziel": "O", "S_neu": 8, "O_neu": 1, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-006-F1-FM2": [
        {"name": "Δp-Monitoring über Kondensator", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Differenzdruck-Messung über Kondensator, Alarm bei Anstieg",
         "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Fouling erhöht Δp"},
        {"name": "Reinigungsintervall", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Feste Revisionsintervalle für Kondensator-Reinigung",
         "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "O sinkt durch präventive Reinigung"},
    ],
    "KOMP-006-F1-FM3": [
        {"name": "TI am Kühlwasser-Rücklauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Temperaturanzeige am Kühlwasser-Rücklauf, Alarm bei < 10 °C",
         "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 3,
         "begruendung": "D sinkt: Erkennt zu kaltes Kühlwasser vor Vereisung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-006-F1-FM4": [
        {"name": "Leitfähigkeitsmessung Kühlwasser", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Leitfähigkeitsüberwachung im Kühlwasserkreislauf erkennt Produkteintritt",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3,
         "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ höherer Aufwand, 💰 moderat"},
        {"name": "Regelmäßige Inspektion", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Rohrprüfung bei Revisionsöffnung",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4,
         "begruendung": "D sinkt: Degradation vor Leckage erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    # KOMP-007: Kondensator KD-102
    "KOMP-007-F1-FM1": [
        {"name": "FI am Kühlwassereinlauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Durchflussmessung am Kühlwassereinlauf mit Alarm bei Unterschreitung",
         "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3, "begruendung": "D sinkt: Direkte Durchflussüberwachung",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Stellungsüberwachung Kühlwasserventil", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Endlagenschalter oder Stellungsrückmeldung", "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3, "begruendung": "Erkennt geschlossenes Ventil",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Wartungsplan Kühlwasserpumpe", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Regelmäßige Inspektion und Wartung", "ziel": "O", "S_neu": 8, "O_neu": 1, "D_neu": 4, "begruendung": "O sinkt durch präventive Wartung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-007-F1-FM2": [
        {"name": "Δp-Monitoring über Kondensator", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Differenzdruck-Messung, Alarm bei Anstieg", "ziel": "D", "S_neu": 8, "O_neu": 3, "D_neu": 3, "begruendung": "D sinkt: Fouling erhöht Δp",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
        {"name": "Reinigungsintervall", "stop_kategorie": "O", "abe_kategorie": "A",
         "beschreibung": "Feste Revisionsintervalle für Kondensator-Reinigung", "ziel": "O", "S_neu": 8, "O_neu": 2, "D_neu": 4, "begruendung": "O sinkt durch präventive Reinigung",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
    "KOMP-007-F1-FM3": [
        {"name": "TI am Kühlwasser-Rücklauf", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Temperaturanzeige am Rücklauf, Alarm bei < 10 °C", "ziel": "D", "S_neu": 6, "O_neu": 3, "D_neu": 3, "begruendung": "D sinkt: Erkennt zu kaltes Kühlwasser",
         "hinweis": "⚡ moderater Aufwand, 💰 gering"},
    ],
    "KOMP-007-F1-FM4": [
        {"name": "Leitfähigkeitsmessung Kühlwasser", "stop_kategorie": "T", "abe_kategorie": "B",
         "beschreibung": "Leitfähigkeitsüberwachung erkennt Produkteintritt", "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 3, "begruendung": "D sinkt: Direkte Leckageerkennung",
         "hinweis": "⚡ höherer Aufwand, 💰 moderat"},
        {"name": "Regelmäßige Inspektion", "stop_kategorie": "O", "abe_kategorie": "B",
         "beschreibung": "Rohrprüfung bei Revisionsöffnung", "ziel": "D", "S_neu": 8, "O_neu": 2, "D_neu": 4, "begruendung": "D sinkt: Degradation vor Leckage erkennbar",
         "hinweis": "⚡ schnell umsetzbar, 💰 gering"},
    ],
}


def get_measures_for_fehlermodus(fehler_id: str, fehlermodus: str, komponente: str) -> list:
    """
    Liefert explizite Maßnahmen für den Fehlermodus.
    Rückgabe: Liste von Maßnahme-Dicts oder [] wenn keine definiert.
    """
    return _MEASURES.get(fehler_id, [])
